apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: controller
  name: multi-john-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: controller
  name: multi-john-controller
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: controller
  name: multi-john-controller
subjects:
  - kind: ServiceAccount
    name: multi-john-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multi-john-controller
