apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: etcd
  name: etcd
spec:
  ports:
    - name: client
      port: {{ .Values.etcd.port }}
      targetPort: client
    - name: peer
      port: {{ .Values.etcd.peerPort }}
      targetPort: peer
  selector:
    io.kompose.service: etcd
status:
  loadBalancer: {}
