apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: howdy
  name: howdy
spec:
  ports:
    - name: http
      port: {{ .Values.multijohn.howdy.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: howdy
  type: {{ .Values.multijohn.howdy.serviceType }}
