apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: etcd
  name: etcd
spec:
  replicas: {{ int .Values.etcd.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: multi-john
      app.kubernetes.io/component: etcd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: multi-john
        app.kubernetes.io/component: etcd
    spec:
      containers:
        - command:
            - /usr/local/bin/etcd
          args:
            - --name=etcd
            - --data-dir=/etcd-data
            - {{ printf "--listen-client-urls=%s" .Values.etcd.listenClientURLs | quote }}
            - {{ printf "--advertise-client-urls=%s" .Values.etcd.advertiseClientURLs | quote }}
            - {{ printf "--listen-peer-urls=%s" .Values.etcd.listenPeerURLs | quote }}
            - {{ printf "--initial-advertise-peer-urls=%s" .Values.etcd.initialAdvertisePeerURLs | quote }}
            - {{ printf "--initial-cluster=%s" .Values.etcd.initialCluster | quote }}
            - --initial-cluster-state=new
            - --log-level=info
            - --logger=zap
            - --log-outputs=stderr
          image: "{{ .Values.etcd.imageName }}"
          imagePullPolicy: {{ .Values.etcd.imagePullPolicy }}
          name: etcd
          ports:
            - name: client
              containerPort: {{ int .Values.etcd.port }}
            - name: peer
              containerPort: {{ int .Values.etcd.peerPort }}
          resources:
              requests:
                memory: {{ .Values.etcd.requests.memory }}
                cpu: {{ .Values.etcd.requests.cpu }}
              limits:
                memory: {{ .Values.etcd.limits.memory }}
                cpu: {{ .Values.etcd.limits.cpu }}
          volumeMounts:
            - mountPath: /etcd-data
              name: data
      restartPolicy: Always
      volumes:
        - name: data
          emptyDir: {}
