apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: etcd
  name: etcd
spec:
  ports:
    - name: client
      port: {{ .Values.etcd.port }}
      targetPort: client
    - name: peer
      port: {{ .Values.etcd.peerPort }}
      targetPort: peer
  selector:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: etcd
