{{- if and .Values.multijohn.work.enabled (not .Values.multijohn.work.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: multi-john
    app.kubernetes.io/component: work
  name: {{ .Values.multijohn.work.name }}
  {{- with .Values.multijohn.work.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
{{- toYaml .Values.multijohn.work.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.multijohn.work.size | quote }}
  {{- if .Values.multijohn.work.storageClassName }}
  storageClassName: {{ .Values.multijohn.work.storageClassName | quote }}
  {{- end }}
{{- end }}
